name: .NET - Build and check format
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: 'latest'
      working-directory:
        required: false
        type: string
        default: '.'
jobs:
  dotnet:
    name: .NET - Build and check format
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:${{ inputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4     
      - name: Check .NET version
        run: dotnet --version       
      - name: Build .NET solution
        run: dotnet build
        working-directory: ${{ inputs.working-directory }}
      - name: Check .NET code format
        run: dotnet format --verify-no-changes
        working-directory: ${{ inputs.working-directory }}
